name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: 'Create Releases'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Release Script
        run: |
          ./.github/workflows/scripts/release.sh
